### ISSUE TITLE
Flask-Dance sends expired token to Azure

### ISSUE THREAD

**Issue by leonbrag** [singingwolfboy/flask-dance#152] opened 2018-08-01 19:02 UTC
Repro:
1. authenticate w/Azure
2. go to the web site again after token expired
3. observe no prompt and internal server error

Logs:
```
2018-08-01T18:56:43.143297497Z [2018-08-01 18:56:43,142] ERROR in app: Exception on / [GET]
2018-08-01T18:56:43.143302298Z Traceback (most recent call last):
2018-08-01T18:56:43.143305898Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-08-01T18:56:43.143309798Z     response = self.full_dispatch_request()
2018-08-01T18:56:43.143313498Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-08-01T18:56:43.143317198Z     rv = self.handle_user_exception(e)
2018-08-01T18:56:43.143320798Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-08-01T18:56:43.143324398Z     reraise(exc_type, exc_value, tb)
2018-08-01T18:56:43.143327798Z   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-08-01T18:56:43.143331399Z     raise value
2018-08-01T18:56:43.143334799Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-08-01T18:56:43.143338399Z     rv = self.dispatch_request()
2018-08-01T18:56:43.143341799Z   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-08-01T18:56:43.143345399Z     return self.view_functions[rule.endpoint](**req.view_args)
2018-08-01T18:56:43.143348799Z   File "./main.py", line 27, in hello_world
2018-08-01T18:56:43.143361300Z     resp = azure.get("/v1.0/me")
2018-08-01T18:56:43.143365400Z   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
2018-08-01T18:56:43.143369000Z     return self.request('GET', url, **kwargs)
2018-08-01T18:56:43.143372600Z   File "/usr/local/lib/python3.6/site-packages/flask_dance/consumer/requests.py", line 141, in request
2018-08-01T18:56:43.143376100Z     **kwargs
2018-08-01T18:56:43.143379500Z   File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 330, in request
2018-08-01T18:56:43.143383100Z     http_method=method, body=data, headers=headers)
2018-08-01T18:56:43.143386600Z   File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 196, in add_token
2018-08-01T18:56:43.143390201Z     raise TokenExpiredError()
2018-08-01T18:56:43.143393701Z oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 
```

Should not Flask-Dance handle it and prompt for authentication again (instead of internal error)?

**Comment by singingwolfboy** [comment] 2018-08-02 19:14
Duplicate of #143.

**Closed by singingwolfboy** 2018-08-02 19:14 UTC
