### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.TokenExpiredError

### ISSUE THREAD

**Issue by flamusdiu** [singingwolfboy/flask-dance#21] opened 2015-06-03 23:06 UTC
I started a StackOverFlow question: [Flask-Dance and TokenExpiredError](http://stackoverflow.com/questions/30606763/flask-dance-and-tokenexpirederror)

I am only using Flask Sessions (atm) as the backend. I've had this error for a while now and I can't seem to even get a new reprompt of the Google page. 

I was wondering if anyone else had any ideas.

**Comment by singingwolfboy** [comment] 2015-07-13 23:14
Are you still having this issue? Is there any more detail you can provide? I'm not sure if this is a problem with Flask-Dance, or with the way you have your code set up. Also, it seems like the StackOverflow question is the best place to get an answer, since you have more detail.

**Comment by flamusdiu** [comment] 2015-07-14 01:24
@singingwolfboy Yes, I am still getting it. I did post it there but no response. I have no idea why it's doing this either. =(

**Comment by singingwolfboy** [comment] 2015-07-23 18:25
Well, with no further details or information, and the fact that I can't reproduce this, I'm going to assume that the problem is due to the way you have your code set up. I'm closing this issue.

**Closed by singingwolfboy** 2015-07-23 18:25 UTC

**Comment by flamusdiu** [comment] 2015-07-24 15:27
@singingwolfboy I have been heavily working lately so I haven't revisited the project. I'll make sure everything is up-to-date with the depends and see if I get the same issue and let you know.
