### ISSUE TITLE
Unmanaged access of declarative attribute __tablename__

### ISSUE THREAD

**Issue by citizenken** [singingwolfboy/flask-dance#42] opened 2015-12-22 16:11 UTC
When I start up my Flask app, I get the following warning:

    /repo/package_venv/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py:173: 
    SAWarning: Unmanaged access of declarative attribute __tablename__ 
    from non-mapped class OAuthConsumerMixin(desc.fget.__name__, cls.__name__))

Looking at the mixin, it is because __tablename__ is a function instead of a property of the mixin. You pass cls into that function to dynamically create the tablename. Is there a way to fix this?

**Comment by singingwolfboy** [comment] 2015-12-22 16:47
I don't understand: [the SQLAlchemy docs follow this exact pattern for attributes on mixin classes](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/declarative/mixins.htm). Can you provide a code snippet that demonstrates the problem -- or even better, an automated test?

**Comment by citizenken** [comment] 2015-12-28 21:41
I don't really understand either. I implement your mixin like so:
    
    class OAuth(db.Model, OAuthConsumerMixin):
        pass

Just like in the examples you use. When I start up the app, with just python `my_app.py -d` I get the above warning. When I go into your mixin file I see these lines, just like in the sqlalchemy example:

    @declared_attr
    def __tablename__(cls):
        return "flask_dance_{}".format(cls.__name__.lower())

When I change that line to this:

`_tablename__ = "flask_dance_oauthconsumermixin"`

I don't see that error in the console any longer.

**Comment by singingwolfboy** [comment] 2015-12-31 19:05
I did some sleuthing, and discovered that the problem is Flask-SQLAlchemy. I've found two related issues: https://github.com/mitsuhiko/flask-sqlalchemy/issues/349 and https://github.com/mitsuhiko/flask-sqlalchemy/issues/323. Hopefully, the next version of Flask-SQLAlchemy will fix this issue.

Regardless, it's not the fault of Flask-Dance, nor is it actually causing any problems, as far as I can see (just raising a warning). As a result, I'm closing this issue.

**Closed by singingwolfboy** 2015-12-31 19:05 UTC

**Comment by singingwolfboy** [comment] 2015-12-31 19:07
You can also make the warning go away by specifying your own `__tablename__` attribute. For example:
```python
class OAuth(db.Model, OAuthConsumerMixin):
    __tablename__ = "flask_dance_oauth"
    pass
```

**Comment by citizenken** [comment] 2016-01-04 14:55
Great, thanks for the investigation work/helpful response. This library has been great to work with.

**Comment by Bachmann1234** [comment] 2016-09-19 01:30
Hah, I ran into the same issue just now :-P

**Comment by r4cs** [comment] 2021-03-19 20:45
> You can also make the warning go away by specifying your own `__tablename__` attribute. For example:
> 
> ```python
> class OAuth(db.Model, OAuthConsumerMixin):
>     __tablename__ = "flask_dance_oauth"
> ```

Not working for me, any tips?
the code get stucks in oauth=query.one() and return that psycopg2 cant find flask_dance_oauth in tables
I am using Flask-SQLAlchemy==2.4.4, SqlAlchemy==1.3.23, SQLAlchemy-Utils==0.36.8
